:toc:
:toc-placement!:

=	hugo-mod-time

:repo-status: https://www.repostatus.org/
:wip: {repo-status}=wip
:wip-svg: {repo-status}badges/latest/wip.svg

image:{wip-svg}["Project Status: WIP – Initial development is in progress, but there has not yet
been a stable, usable release suitable for the public.", link={wip}]

[NOTE]
This module is still in early development. The partial names and available options may change in
future versions. Hopefully there will be few breaking changes, and warnings will be used where
possible to signal deprecated options.

:Hugo: https://gohugo.io/
:relative-time-element: https://github.com/github/relative-time-element

A module for the {Hugo}[Hugo] static site generator, which generates correctly formatted `<time>`
elements. It also supports ordinals for day formatting. Additionally, it supports including GitHub's
{relative-time-element}[relative-time-element] package, automatically updating dates and times on
the client, according to their location.

toc::[]

==	Installation

Add hugo-mod-time to your Hugo project configuration:

-	config.toml
+
[source,toml]
----
[module]
[[module.imports]]
path = 'github.com/kcastellino/hugo-mod-time'
----

-	config.yaml
+
[source,yaml]
----
module:
  imports:
    - path: github.com/kcastellino/hugo-mod-time
----

If you are not using the <<client-side-time-conversion>> option, and you don't want to import the
third-party module for that feature, set `ignoreImports` on the module import to `true`:

-	config.toml
+
[source,toml]
----
[module]
[[module.imports]]
path = 'github.com/kcastellino/hugo-mod-time'
ignoreImports = true
----

-	config.yaml
+
[source,yaml]
----
module:
  imports:
    - path: github.com/kcastellino/hugo-mod-time
	  ignoreImports: true
----

==	How to use

To insert a date without a time, use the `date` partial with an appropriate format string:

[source,go-html-template]
----
{{ partial "date" (dict "Time" $time "Format" "2 January 2006") }}
----

To insert a complete datetime, use the `time` partial:

[source,go-html-template]
----
{{ partial "time" (dict "Time" $time "Format" "2 January 2006 3:04 PM MST") }}
----

:relative-time-attrs: {relative-time-element}#attributes

Both partials take a dictionary as the 'context' (the single argument), which requires the
following properties:

Time::
A https://godoc.org/time#Time[`time.Time`] struct. Page variables such as
`.PublishDate`` and `.Lastmod` can be passed straight into this argument;
timestamps can be converted to objects using Hugo's https://gohugo.io/functions/time/[`time` function].

Format::
A https://gohugo.io/functions/format/#gos-layout-string[Go Layout String] as used by
the `time.Format` function to render a datetime.

Options::
A dictionary containing key-value pairs corresponding to the
{relative-time-attrs}[attributes for the
`<relative-time>` element]

The `time` partial above will produce the following HTML:

[source,html]
----
<time datetime="2023-01-30T00:00:00+1100">30 January 2023 12:00 AM AEDT</time>
----

===	Using ordinals in dates

With the `date` and `time` partials, you can also use an ordinal in the layout string to signify
you would like dates to be formatted as such:

[source,go-html-template]
----
{{ partial "date" (dict "Time" $time "Format" "January 2nd 2006") }}
----

This case is specially handled to produce the following HTML:

[source,html]
----
<time datetime="2023-01-30">January 30th 2023</time>
----

[#client-side-time-conversion, reftext="client-side time conversion"]
==	Enabling client-side time conversion

Client-side time conversion is not enabled by default, as it requires including
{relative-time-element}[relative-time-element] as an additional dependency. To enable it, you need
to set `params.time.enableRelative` in your config to `true`.

-	config.toml:
+
[source,toml]
----
[params.time]
enableRelative = true
----

-	config.yaml:
+
[source,yaml]
----
params:
  time:
  enableRelative: true
----

:js-build-options: https://gohugo.io/hugo-pipes/js/#options

You will also need to include the JavaScript files required to enable the custom elements used.
The simple option is to just include the `relative-time-element/script-src` partial in your `<head>`,
along with a dictionary providing {js-build-options}[options to js.Build].

[source,html]
----
<head>
	<!-- omitted -->
	{{ partialCached "relative-time-element/script-src" (dict "target" "es2017" "minify" hugo.IsProduction) }}
</head>
----

[TIP]
If you do not wish to set any options, you can use the `dict` function with no options to pass an
empty dictionary.

[NOTE]
Previous versions of this module used a partial at "time/script-import.html" to build and include
the JavaScript files, which took no options. This partial has been preserved for backwards
compatibility.

Alternatively, you can import `/assets/relative-time-element/index.ts` into your own bundle.

After enabling relative time conversion, the generated HTML will look like this:

[source,html]
----
<time datetime="2023-01-30T00:00:00+1100">
	<relative-time datetime="2023-01-30T00:00:00+1100"
		month="long" day="numeric" year="numeric"
		hour="numeric" minute="2-digit" timezonename="short">
		30 January 2023 12:00 AM AEDT
	</relative-time>
</time>
----

The template will use the provided layout string to automatically configure the `relative-time`
element so it will match as close as possible to the date format produced by Hugo.

===	Additional options

You may pass in options to change the appearance of the `relative-time` element, by passing in an
options dictionary. You can configure the element using {relative-time-attrs}[any available attribute].

[source,go-html-template]
----
{{ $timeOptions := dict "format" "relative" "precision" "day" "threshold" "P7D" }}

{{ partial "time" (dict "Time" $time "Format" "2 January 2006 3:04 PM MST" "Options" $timeOptions) }}
----

A default configuration can be provided by setting `params.time.defaultOptions` in your site config:

-	config.toml:
+
[source,toml]
----
[params.time]
enableRelative = true

[params.time.defaultOptions]
format = "relative"
precision = "day"
threshold = "P7D"
----

-	config.yaml:
+
[source,yaml]
----
params:
  time:
  enableRelative: true
  defaultOptions:
    format: "relative"
    precision: "day"
    threshold: "P7D"
----

==	Licensing and contributions

This module is licensed under the University of Illinois/NCSA license, which can be read in
link:LICENSE.txt[]. It is legally identical to the 3-clause "Modified" BSD License, and contains an
extra clause (Clause 3) compared to the MIT license.

By default, using this module will download the `relative-time-element` package to your computer,
which is created by GitHub, Inc. and licensed under the {relative-time-element}/blob/main/LICENSE[MIT license].
If you don't want to download this package,
xref:installation[set `ignoreImports` under your module import to `true`]. Additionally, the
`<relative-time>` element will not be used on generated pages, and the JavaScript package will not
be distributed to clients, unless the xref:client-side-time-conversion[`enableRelative` option is set to true].

Contributions to this module are welcome! To contribute, please feel free to create an issue or a
pull request in this repository.
